version: '3.8'   
services:
  customerdb:
    container_name: ${POSTGRES_HOST}
    hostname: ${POSTGRES_HOST}
    image: postgres
    ports:
      - "54321:${POSTGRES_PORT}"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
    volumes:
      - /data/volumes/myproject/my_db:/var/lib/postgresql/data/

  kotlincrud:
    container_name: kotlincrud
    hostname: kotlincrud
    image: kotlincrud
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

